export const sliderData = [
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 1 행사",
    location: "서울 서초구",
    period: "2025. 4. 1 ~ 2025. 4. 3",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 1 행사",
    location: "서울 서초구",
    period: "2025. 4. 1 ~ 2025. 4. 3",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 1 행사",
    location: "서울 서초구",
    period: "2025. 4. 1 ~ 2025. 4. 3",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 2 행사",
    location: "서울 서초구",
    period: "2025. 4. 4 ~ 2025. 4. 6",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 2 행사",
    location: "서울 서초구",
    period: "2025. 4. 4 ~ 2025. 4. 6",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 2 행사",
    location: "서울 서초구",
    period: "2025. 4. 4 ~ 2025. 4. 6",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 2 행사",
    location: "서울 서초구",
    period: "2025. 4. 4 ~ 2025. 4. 6",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 3 행사",
    location: "서울 서초구",
    period: "2025. 4. 7 ~ 2025. 4. 9",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 3 행사",
    location: "서울 서초구",
    period: "2025. 4. 7 ~ 2025. 4. 9",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 3 행사",
    location: "서울 서초구",
    period: "2025. 4. 7 ~ 2025. 4. 9",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 3 행사",
    location: "서울 서초구",
    period: "2025. 4. 7 ~ 2025. 4. 9",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 4 행사",
    location: "서울 서초구",
    period: "2025. 4. 10 ~ 2025. 4. 12",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 4 행사",
    location: "서울 서초구",
    period: "2025. 4. 10 ~ 2025. 4. 12",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 4 행사",
    location: "서울 서초구",
    period: "2025. 4. 10 ~ 2025. 4. 12",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 5 행사",
    location: "서울 서초구",
    period: "2025. 4. 13 ~ 2025. 4. 15",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 5 행사",
    location: "서울 서초구",
    period: "2025. 4. 13 ~ 2025. 4. 15",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 5 행사",
    location: "서울 서초구",
    period: "2025. 4. 13 ~ 2025. 4. 15",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 6 행사",
    location: "서울 서초구",
    period: "2025. 4. 16 ~ 2025. 4. 18",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 6 행사",
    location: "서울 서초구",
    period: "2025. 4. 16 ~ 2025. 4. 18",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 6 행사",
    location: "서울 서초구",
    period: "2025. 4. 16 ~ 2025. 4. 18",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 7 행사",
    location: "서울 서초구",
    period: "2025. 4. 19 ~ 2025. 4. 21",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 7 행사",
    location: "서울 서초구",
    period: "2025. 4. 19 ~ 2025. 4. 21",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 7 행사",
    location: "서울 서초구",
    period: "2025. 4. 19 ~ 2025. 4. 21",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 7 행사",
    location: "서울 서초구",
    period: "2025. 4. 19 ~ 2025. 4. 21",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 8 행사",
    location: "서울 서초구",
    period: "2025. 4. 22 ~ 2025. 4. 24",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 8 행사",
    location: "서울 서초구",
    period: "2025. 4. 22 ~ 2025. 4. 24",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 8 행사",
    location: "서울 서초구",
    period: "2025. 4. 22 ~ 2025. 4. 24",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 9 행사",
    location: "서울 서초구",
    period: "2025. 4. 25 ~ 2025. 4. 27",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 9 행사",
    location: "서울 서초구",
    period: "2025. 4. 25 ~ 2025. 4. 27",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 9 행사",
    location: "서울 서초구",
    period: "2025. 4. 25 ~ 2025. 4. 27",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 9 행사",
    location: "서울 서초구",
    period: "2025. 4. 25 ~ 2025. 4. 27",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 10 행사",
    location: "서울 서초구",
    period: "2025. 4. 28 ~ 2025. 4. 30",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 10 행사",
    location: "서울 서초구",
    period: "2025. 4. 28 ~ 2025. 4. 30",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 10 행사",
    location: "서울 서초구",
    period: "2025. 4. 28 ~ 2025. 4. 30",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-1.jpg",
    title: "(4월) - 10 행사",
    location: "서울 서초구",
    period: "2025. 4. 28 ~ 2025. 4. 30",
    place: "서울특별시 서대문구 통일로 279-24 (현저동)",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 1 행사",
    location: "서울 강남구",
    period: "2025. 5. 1 ~ 2025. 5. 3",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 1 행사",
    location: "서울 강남구",
    period: "2025. 5. 1 ~ 2025. 5. 3",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 1 행사",
    location: "서울 강남구",
    period: "2025. 5. 1 ~ 2025. 5. 3",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 2 행사",
    location: "서울 강남구",
    period: "2025. 5. 4 ~ 2025. 5. 6",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 2 행사",
    location: "서울 강남구",
    period: "2025. 5. 4 ~ 2025. 5. 6",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 2 행사",
    location: "서울 강남구",
    period: "2025. 5. 4 ~ 2025. 5. 6",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 3 행사",
    location: "서울 강남구",
    period: "2025. 5. 7 ~ 2025. 5. 9",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 3 행사",
    location: "서울 강남구",
    period: "2025. 5. 7 ~ 2025. 5. 9",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 3 행사",
    location: "서울 강남구",
    period: "2025. 5. 7 ~ 2025. 5. 9",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 4 행사",
    location: "서울 강남구",
    period: "2025. 5. 10 ~ 2025. 5. 12",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 4 행사",
    location: "서울 강남구",
    period: "2025. 5. 10 ~ 2025. 5. 12",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 4 행사",
    location: "서울 강남구",
    period: "2025. 5. 10 ~ 2025. 5. 12",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 5 행사",
    location: "서울 강남구",
    period: "2025. 5. 13 ~ 2025. 5. 15",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 5 행사",
    location: "서울 강남구",
    period: "2025. 5. 13 ~ 2025. 5. 15",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 5 행사",
    location: "서울 강남구",
    period: "2025. 5. 13 ~ 2025. 5. 15",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 6 행사",
    location: "서울 강남구",
    period: "2025. 5. 16 ~ 2025. 5. 18",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 6 행사",
    location: "서울 강남구",
    period: "2025. 5. 16 ~ 2025. 5. 18",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 6 행사",
    location: "서울 강남구",
    period: "2025. 5. 16 ~ 2025. 5. 18",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 6 행사",
    location: "서울 강남구",
    period: "2025. 5. 16 ~ 2025. 5. 18",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 7 행사",
    location: "서울 강남구",
    period: "2025. 5. 19 ~ 2025. 5. 21",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 7 행사",
    location: "서울 강남구",
    period: "2025. 5. 19 ~ 2025. 5. 21",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 7 행사",
    location: "서울 강남구",
    period: "2025. 5. 19 ~ 2025. 5. 21",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 7 행사",
    location: "서울 강남구",
    period: "2025. 5. 19 ~ 2025. 5. 21",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 8 행사",
    location: "서울 강남구",
    period: "2025. 5. 22 ~ 2025. 5. 24",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 8 행사",
    location: "서울 강남구",
    period: "2025. 5. 22 ~ 2025. 5. 24",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 8 행사",
    location: "서울 강남구",
    period: "2025. 5. 22 ~ 2025. 5. 24",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 9 행사",
    location: "서울 강남구",
    period: "2025. 5. 25 ~ 2025. 5. 27",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 9 행사",
    location: "서울 강남구",
    period: "2025. 5. 25 ~ 2025. 5. 27",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 9 행사",
    location: "서울 강남구",
    period: "2025. 5. 25 ~ 2025. 5. 27",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 10 행사",
    location: "서울 강남구",
    period: "2025. 5. 28 ~ 2025. 5. 30",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 10 행사",
    location: "서울 강남구",
    period: "2025. 5. 28 ~ 2025. 5. 30",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-2.jpg",
    title: "(5월) - 10 행사",
    location: "서울 강남구",
    period: "2025. 5. 28 ~ 2025. 5. 30",
    place: "서울특별시 강남구 테헤란로 123",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 1 행사",
    location: "서울 종로구",
    period: "2025. 6. 1 ~ 2025. 6. 3",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 1 행사",
    location: "서울 종로구",
    period: "2025. 6. 1 ~ 2025. 6. 3",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 1 행사",
    location: "서울 종로구",
    period: "2025. 6. 1 ~ 2025. 6. 3",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 2 행사",
    location: "서울 종로구",
    period: "2025. 6. 4 ~ 2025. 6. 6",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 2 행사",
    location: "서울 종로구",
    period: "2025. 6. 4 ~ 2025. 6. 6",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 2 행사",
    location: "서울 종로구",
    period: "2025. 6. 4 ~ 2025. 6. 6",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 2 행사",
    location: "서울 종로구",
    period: "2025. 6. 4 ~ 2025. 6. 6",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 3 행사",
    location: "서울 종로구",
    period: "2025. 6. 7 ~ 2025. 6. 9",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 3 행사",
    location: "서울 종로구",
    period: "2025. 6. 7 ~ 2025. 6. 9",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 3 행사",
    location: "서울 종로구",
    period: "2025. 6. 7 ~ 2025. 6. 9",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 3 행사",
    location: "서울 종로구",
    period: "2025. 6. 7 ~ 2025. 6. 9",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 4 행사",
    location: "서울 종로구",
    period: "2025. 6. 10 ~ 2025. 6. 12",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 4 행사",
    location: "서울 종로구",
    period: "2025. 6. 10 ~ 2025. 6. 12",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 4 행사",
    location: "서울 종로구",
    period: "2025. 6. 10 ~ 2025. 6. 12",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 5 행사",
    location: "서울 종로구",
    period: "2025. 6. 13 ~ 2025. 6. 15",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 5 행사",
    location: "서울 종로구",
    period: "2025. 6. 13 ~ 2025. 6. 15",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 5 행사",
    location: "서울 종로구",
    period: "2025. 6. 13 ~ 2025. 6. 15",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 5 행사",
    location: "서울 종로구",
    period: "2025. 6. 13 ~ 2025. 6. 15",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 6 행사",
    location: "서울 종로구",
    period: "2025. 6. 16 ~ 2025. 6. 18",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 6 행사",
    location: "서울 종로구",
    period: "2025. 6. 16 ~ 2025. 6. 18",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 6 행사",
    location: "서울 종로구",
    period: "2025. 6. 16 ~ 2025. 6. 18",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 6 행사",
    location: "서울 종로구",
    period: "2025. 6. 16 ~ 2025. 6. 18",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 7 행사",
    location: "서울 종로구",
    period: "2025. 6. 19 ~ 2025. 6. 21",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 7 행사",
    location: "서울 종로구",
    period: "2025. 6. 19 ~ 2025. 6. 21",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 7 행사",
    location: "서울 종로구",
    period: "2025. 6. 19 ~ 2025. 6. 21",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 7 행사",
    location: "서울 종로구",
    period: "2025. 6. 19 ~ 2025. 6. 21",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 8 행사",
    location: "서울 종로구",
    period: "2025. 6. 22 ~ 2025. 6. 24",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 8 행사",
    location: "서울 종로구",
    period: "2025. 6. 22 ~ 2025. 6. 24",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 8 행사",
    location: "서울 종로구",
    period: "2025. 6. 22 ~ 2025. 6. 24",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 9 행사",
    location: "서울 종로구",
    period: "2025. 6. 25 ~ 2025. 6. 27",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 9 행사",
    location: "서울 종로구",
    period: "2025. 6. 25 ~ 2025. 6. 27",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 9 행사",
    location: "서울 종로구",
    period: "2025. 6. 25 ~ 2025. 6. 27",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 10 행사",
    location: "서울 종로구",
    period: "2025. 6. 28 ~ 2025. 6. 30",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 10 행사",
    location: "서울 종로구",
    period: "2025. 6. 28 ~ 2025. 6. 30",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 10 행사",
    location: "서울 종로구",
    period: "2025. 6. 28 ~ 2025. 6. 30",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
  {
    img: "../img/area/slider/slider-3.jpg",
    title: "(6월) - 10 행사",
    location: "서울 종로구",
    period: "2025. 6. 28 ~ 2025. 6. 30",
    place: "서울특별시 종로구 세종대로 110",
    link: "https://github.com/vargun",
  },
];
